### ISSUE TITLE
ImportError: No module named fcntl

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init-babel#145]
When I try to run gulp,  it requires fcntl module, which only available on Unix machine?
I am running windows 10.
-----------------------
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "C:\Developer\fakemail\main\main.py", line 5, in <module>
    import flask_babel
  File "lib\flask_babel\__init__.py", line 18, in <module>
    from babel import dates, numbers, support, Locale
  File "lib\babel\dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "lib\babel\util.py", line 19, in <module>
    from babel import localtime
  File "lib\babel\localtime\__init__.py", line 23, in <module>
    from babel.localtime._unix import _get_localzone
  File "lib\babel\localtime\_unix.py", line 6, in <module>
    import subprocess
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\python\runtime\sandbox.py", line 1043, in load_module
    return self.import_stub_module(fullname)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\devappserver2\python\runtime\sandbox.py", line 1049, in import_stub_module
    __import__(fullname, {}, {})
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\dist27\subprocess.py", line 8, in <module>
    from python_std_lib import subprocess
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\dist27\python_std_lib\subprocess.py", line 429, in <module>
    import fcntl
ImportError: No module named fcntl

**Comment by do-n-khanh** [comment]
I fixed it by change ...\main\lib\babel\localtime\__init__.py file as below.

from babel.localtime._win32 import _get_localzone
# if sys.platform == 'win32':
#     from babel.localtime._win32 import _get_localzone
# else:
#     from babel.localtime._unix import _get_localzone
