### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'lib.zip/babel/locale-data'"

### ISSUE THREAD

**Issue by patrickmpoon** [gae-init/gae-init-babel#79]
Deploying the latest commit, `09294baaceee90a2a80fae8efcf7ddf9d3c21d4e`, to a new project in the cloud, I see the error above in the log files after attempting to go to the main landing page, which shows the standard gae-init-babel error template message:  "Oh no...! Something went wrong :(  Please check back in a bit."  I spent a full day trying to figure out how to resolve it, but am stumped.  Here is the full error message in the logs:
```
Exception on / [GET] (lib.zip/flask/app.py:1761)
Traceback (most recent call last):
  File "lib.zip/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "lib.zip/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "lib.zip/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "lib.zip/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/base/data/home/apps/p~pp-gae-init-babel-1/20180709t231028.411026440181713499/control/error.py", line 48, in production_error_handler
    return error_handler(e)
  File "/base/data/home/apps/p~pp-gae-init-babel-1/20180709t231028.411026440181713499/control/error.py", line 41, in error_handler
    error=e,
  File "lib.zip/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "lib.zip/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "lib.zip/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "lib.zip/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/p~pp-gae-init-babel-1/20180709t231028.411026440181713499/templates/error.html", line 1, in top-level template code
    # extends 'base.html'
OSError: [Errno 2] No such file or directory: 'lib.zip/babel/locale-data'
```
As a sanity check, I downloaded the application code from the deployed instance, unzipped `lib.zip`, and verified that the `babel/locale-data` directory existed and contained the expected *.dat files.

The repo does work fine on a local dev server, by the way.

On a side note, the last merged commit for this repository that I was able to deploy to the cloud without encountering an error page is `d9344574badbe1d476eb7b834a039a3a632a315e`, which is dated 1/12/18.  The core gae-init repo is working fine out-of-the-box (so far).

**Comment by patrickmpoon** [comment]
To get around this for now, I removed the `- ^lib/.*` line from app.yaml and replaced `sys_path_insert('lib.zip')` in appengine_config.py with `vendor.add('lib')`.  Also added `from google.appengine.ext import vendor` at the top of this file.

The file count deployed is ~2500 -- well within the 10,000 file count limit.

**Comment by lipis** [comment]
I get the same error.. but strangely enough it works in one of my other projects! :( Mystery...

**Comment by lipis** [comment]
@patrickmpoon can you try again with this patch? https://github.com/gae-init/gae-init-babel/commit/fe5aa577c6a63b33f71a02646b35a932181e0c3c
